dataset_name: Wiki_WrtFreq0.02_thresh10000_rnd0_RSize8_WSize8_Len5000
func: toYCSB
max_qry_size: 1664
multi_size_qry: true
query_num: 693
rsize: 8
tcache_root: /mnt/d/cc_exp/data/YCSB_new
txn_num: 5000
wrt_freq: 0.02
wsize: 8
ycsb_root: /mnt/d/cc_exp/YCSB/datasets
